version: "3.1"

services:

  db:
    image: mariadb:10.3
    volumes:
      - ./db/proftpd.sql:/docker-entrypoint-initdb.d/proftpd.sql
    environment:
      - MYSQL_ROOT_PASSWORD=0Goc02oC
      - MYSQL_DATABASE=proftpd
      - MYSQL_USER=proftpd
      - MYSQL_PASSWORD=NFvFPGht

  proftpd:
    image: pockost/proftpd
    volumes:
      - ./proftpd/proftpd.conf:/usr/local/etc/proftpd.conf
      - data:/data
      - ssh:/etc/ssh
      - ./proftpd/entrypoint.sh:/entrypoint.sh
    ports:
      - "9920:20"
      - "9921:21"
      - "2222:22"
      - "60000-60100:60000-60100"
    entrypoint: ['sh', '/entrypoint.sh' ]
    command: ["/usr/local/sbin/proftpd", "-n", "-c", "/usr/local/etc/proftpd.conf" ]
    depends_on:
      - db

  ui:
    image: wolpert/proftpmgr
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=proftpd
      - MYSQL_USER=proftpd
      - MYSQL_PASSWORD=NFvFPGht
      - FTP_DATA_DIR=/data
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
    depends_on:
      - db

  cron:
    image: wolpert/proftpmgr
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=proftpd
      - MYSQL_USER=proftpd
      - MYSQL_PASSWORD=NFvFPGht
      - FTP_DATA_DIR=/data
    volumes:
      - data:/data
    entrypoint: crond -f
    depends_on:
      - db

volumes:
  data:
  ssh:
